### ISSUE TITLE
EnvelopesApi updateDocument passing values

### ISSUE THREAD

**Issue by treytt** [docusign/docusign-esign-php-client#158]
Hello, I am trying to rename a document before sending it to be signed. When calling $envelope->updateDocument I am not able send any updated values aside from account_id, document_id, envelope_id

Ref: https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/update/

**Comment by EdwinMoralesDS** [comment]
This issue was recently reported with another SDK, we are tracking this under bug number DCM-6703. Please ask your DocuSign support contact to add your company's information to the bug report. I don't have a schedule for a fix. 


In the meantime, as a workaround, you can try to call the API directly without using the SDK. Another option is to modify your code so it includes the updated name in the API call that creates the envelope, this way the update call is not necessary

**Comment by treytt** [comment]
Thanks much for the response @EdwinMoralesDS, is that possible when calling a template ID? 

`$envelope_definition->setTemplateId('XXX');`

**Comment by EdwinMoralesDS** [comment]
Hello, 

It is possible to change the name of the document but you will have to include the file in your API call. This documents explains how to use composite templates to overwrite the file in your template. 

https://www.docusign.com/blog/dsdev-from-the-trenches-composite-templates

**Comment by jmiller42ce** [comment]
@EdwinMoralesDS can you avoid having to include the file in the API call by passing a `ServerTemplate` in the composite template?

**Comment by shan285** [comment]
Hi @treytt,

I wanted to check in regarding the solution @EdwinMoralesDS  provided to address the "updateDocument" issue. Could you please let me know if it resolved the issue or if there are any outstanding concerns?

Your feedback is greatly appreciated, as it helps ensure that everything is functioning smoothly.

Thank you for your time and assistance.

-Shashanka

**Comment by treytt** [comment]
hey @shan285 we ultimately went with another approach here so cant comment on that. I will happily close this issue.
